### PR TITLE
Fixes and performance

### PR DESCRIPTION
**Pull request by sandraros**
Many changes that I didn't track unfortunately. I won't feel offended if you don't take it ;-)
Let me try to remember what were the problems:
- Very low pretty print performance for variables containing lot of data. Used to timeout after 30 minutes. I guess the fixes made it 5 times faster (but that is still slow).
- Bug if table has component named INDEX
- Bug if tables are hashed
- Bug if tables have unstructured lines
- Bug if character variable contains a quote (should be doubled)
- Enhancement: integer values in VALUE #( ... ) written without quotes
- Enhancement: less expansive right-alignment -> everything well aligned with tabs of 8 characters
- New method debug_debugger_if_needed in ZCL_OP_DEBUGGER_INTEGRATION to help debug the tool inside the debugger (via a static BREAK-POINT statement)

### CODE REVIEW

**Comment by gepparta** [comment]
Hi Sandra, great to see such improvements. 
I will check them as soon as possible and will try to merge.

**Comment by MikeSidorochkin** [comment]
Doesn't work at 7.40 (Last SP):

- type->typekind_int8 - doesn't exists
- where_used_original_dynpro
- button in alv doesn't work

**Comment by sandraros** [comment]
> * button in alv doesn't work

I can do the first 2 requests easily. Concerning the last one, could you post a screenshot please?

**Comment by gepparta** [comment]
Hi @sandraros,
have you checked mentioned issues?
On my 7.40 system I am working currenly on this.
Also please consider that ENUM Type is not available in 7.40 so class  zcl_op_value_pretty_printer must be implemented somehow different.

I propose to use two different branches:
1) for ABAP-7.40 (I will use this one for my changes)
2) ABAP-7.xxx for Abap versions where abap enum type and typekind_int8 exists  

What do you think?

**Comment by sandraros** [comment]
Hi @gepparta. Keeping only one branch is better. What about using [abaplint](https://blogs.sap.com/2020/02/12/abaplint-github-actions-brief-set-up-summary/)? That would permit to have code valid for ABAP 7.02 during the merge (but wouldn't detect things like typekind_int8 -> fix needed).

**Comment by gepparta** [comment]
I have created a 7.40 branch and commited my changes to it.
They are working.
Also I have improved some unittests.

Feel free to try it out.

Note: I don't have a good workaround for "typekind_int8" till now.

I am using abapLint on some repos, never thought about using it here too.
Nice idea. I will definitely think about it.

**Pull request merged**
